---
- name: Crear usuarios en servidores según configuración
  hosts: all
  become: true

  vars:
    usuarios_definidos:
      access:
        password: "{{ 'access' | password_hash('sha512') }}"
        shell: /usr/sbin/nologin
        sudo: false
      sysadmin:
        password: "{{ 'sysadmin' | password_hash('sha512') }}"
        shell: /bin/bash
        sudo: false
      databases:
        password: "{{ 'databases' | password_hash('sha512') }}"
        shell: /bin/bash
        sudo: false
      devops:
        password: "{{ 'devops' | password_hash('sha512') }}"
        shell: /bin/bash
        sudo: false
  
  vars_files:
    - sudo_rules.yml

  tasks:
    - name: Incluir tareas para cada usuario
      include_tasks: crear_usuario_individual.yml
      loop: "{{ usuarios_a_crear | default([]) }}"
      loop_control:
        loop_var: usuario

